name: Thumb
on:
  schedule:
   #- cron: "0 1 * * *"
   - cron: "4,14,24,34,44,54 * * * *"
  workflow_dispatch:
 
#xxx
jobs:
  build:
    runs-on: ubuntu-18.04 #ubuntu-latest
    steps:        
     - name: Download zip
       env:
          url: ${{ secrets.thumburl }}
       run: |
          echo Download dll
          wget -q --output-document=linux-x64.zip $url 
          echo unzip..........
          unzip linux-x64.zip -d linux-x64
          sudo chmod -R +X linux-x64 
          cd linux-x64
          dotnet AutomationGetCorruptedImage.dll
